### ISSUE TITLE
dash mpd 0 segement kills stream

### ISSUE THREAD

**Issue by i2iSteve** [alfg/docker-nginx-vod-module#12]
Having a strange issue with some of our videos where if the mpd shows a segment size 0 the stream stops completely. It can run through VLC and via HLS fine but we are at a loss what to do apart from re encode the files (which would not be a small job)

**Comment by alfg** [comment]
Hey @i2iSteve, this may be related to the nginx module. This repo is just packages it up into a docker image and configuration for use.
