### ISSUE TITLE
我访问一直是502报错

### ISSUE THREAD

**Issue by joykaiyo** [alfg/docker-nginx-vod-module#5]
我是跟着描述去做的，但是不起作用
访问这个链接
http://localhost:8080/hls/video.mp4/master.m3u8
一直报502
报错信息为
nginx-vod_1  | 2018/04/29 04:01:46 [debug] 9#9: accept on 0.0.0.0:80, ready: 0
nginx-vod_1  | 2018/04/29 04:01:46 [debug] 10#10: accept on 0.0.0.0:80, ready: 0
nginx-vod_1  | 2018/04/29 04:01:46 [debug] 10#10: posix_memalign: 000055B7A6E14780:512 @16
nginx-vod_1  | 2018/04/29 04:01:46 [debug] 10#10: *7 accept: 183.45.22.200:22584 fd:8
nginx-vod_1  | 2018/04/29 04:01:46 [debug] 10#10: *7 event timer add: 8: 60000:1524974566881
nginx-vod_1  | 2018/04/29 04:01:46 [debug] 10#10: *7 reusable connection: 1
nginx-vod_1  | 2018/04/29 04:01:46 [debug] 10#10: *7 epoll add event: fd:8 op:1 ev:80002001
nginx-vod_1  | 2018/04/29 04:01:46 [debug] 9#9: accept() not ready (11: Resource temporarily unavailable)

**Comment by alfg** [comment]
Will continue this thread on https://github.com/alfg/docker-nginx-vod-module/issues/4.
