### ISSUE TITLE
docker-compose error at launch

### ISSUE THREAD

**Issue by dgillier** [alfg/docker-nginx-vod-module#7]
Hello,

I'm trying to use your nginx-VOD docker module on a AWS EC2 T2.micro instance without success...

I generate the AWS S3 keys using your script and fill up the docker compose file with them but when I'm running docker-compose up I've got the following errors:

 docker-compose up
Recreating vod ... done
Attaching to vod
vod          | nginx: [alert] mmap(MAP_ANON|MAP_SHARED, 2147483648) failed (12: Out of memory)
vod          | nginx: [alert] munmap(FFFFFFFFFFFFFFFF, 2147483648) failed (22: Invalid argument)
vod exited with code 1

Any idea what's going on ?
Thanks for your help.
Denis

**Comment by alfg** [comment]
Hey @dgillier, 

Sounds like it could be related to lack of memory. Can you try on a larger instance than micro? You can also check your memory usage while it's starting up.

**Comment by dgillier** [comment]
OK Thanks,  I will try that (FYI same instance is running your nginx-rtmp docker image without any problems).

**Comment by alfg** [comment]
Closing for now. Feel free to re-open if you continue to have the issue after trying the method above. Thanks!
