### ISSUE TITLE
Trying DRM setup, wanna help?

### ISSUE THREAD

**Issue by kitobelix** [alfg/docker-nginx-vod-module#8]
Hi Alfred, I'm trying to do a drm setup. Do you want to participate on this? I also have tryed cdn setup, and it's working very well.

**Comment by alfg** [comment]
Hi @jmartincufre, 

Have you checked out the drm branch? I have an example of using widevine, but you'll also need a server to provide keys and a widevine proxy.

https://github.com/alfg/docker-nginx-vod-module/blob/drm/nginx.remote.drm.conf

**Comment by kitobelix** [comment]
No, I haven't but I'm using EZDRM to do the tests. So I'm trying to make mss and dash work, as well as hls with fairplay (when apple authorizes me to do so).

**Comment by kitobelix** [comment]
So far I made it work:

Dash with MS Playready
Dash with G. Widevine

In a few minutes I will tell you if I made MSS work with both PR and WV.

**Comment by alfg** [comment]
I'm not sure if MSS would work with WV.

**Comment by alfg** [comment]
Hey @jmartincufre, any new findings on this? Can this issue be closed?

**Comment by alfg** [comment]
Closing. Feel free to respond to the issue if you have any other questions.
